-- Modelo de Datos para Reporting
-- Empresa ficticia: NovaMarket
-- Ejecutar con psql desde la base de datos de destino.

CREATE SCHEMA IF NOT EXISTS reporting;

SET search_path TO reporting, public;

-- Permite reconstruir el modelo desde cero en un entorno de práctica.
DROP VIEW IF EXISTS reporte_ventas;
DROP TABLE IF EXISTS detalle_ventas;
DROP TABLE IF EXISTS ventas;
DROP TABLE IF EXISTS productos;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    ciudad VARCHAR(80) NOT NULL,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE productos (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    categoria VARCHAR(80) NOT NULL,
    precio NUMERIC(12, 2) NOT NULL CHECK (precio > 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ventas (
    venta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    fecha_venta DATE NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'completada'
        CHECK (estado IN ('completada', 'pendiente', 'cancelada')),
    CONSTRAINT fk_ventas_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes (cliente_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE detalle_ventas (
    venta_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12, 2) NOT NULL CHECK (precio_unitario > 0),
    descuento NUMERIC(12, 2) NOT NULL DEFAULT 0
        CHECK (descuento >= 0 AND descuento <= cantidad * precio_unitario),
    PRIMARY KEY (venta_id, producto_id),
    CONSTRAINT fk_detalle_venta
        FOREIGN KEY (venta_id)
        REFERENCES ventas (venta_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (producto_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_ventas_cliente ON ventas (cliente_id);
CREATE INDEX idx_ventas_fecha ON ventas (fecha_venta);
CREATE INDEX idx_detalle_producto ON detalle_ventas (producto_id);

-- Vista de grano transaccional: una fila por producto vendido dentro de una venta.
-- El precio_unitario queda en el detalle para conservar el precio histórico.
CREATE OR REPLACE VIEW reporte_ventas AS
SELECT
    v.venta_id,
    v.fecha_venta,
    v.estado,
    c.cliente_id,
    c.nombre AS cliente,
    c.email AS cliente_email,
    c.ciudad,
    p.producto_id,
    p.nombre AS producto,
    p.categoria,
    dv.cantidad,
    dv.precio_unitario,
    dv.descuento,
    ROUND((dv.cantidad * dv.precio_unitario) - dv.descuento, 2) AS total_linea
FROM ventas AS v
INNER JOIN clientes AS c
    ON c.cliente_id = v.cliente_id
INNER JOIN detalle_ventas AS dv
    ON dv.venta_id = v.venta_id
INNER JOIN productos AS p
    ON p.producto_id = dv.producto_id;